-- ============================================================================
-- COGNIFY PRODUCTION SUPABASE POSTGRESQL SCHEMA
-- PostgreSQL Compatible Schema with Row Level Security (RLS) & Triggers
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ----------------------------------------------------------------------------
-- 1. CLASSES TABLE
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.classes (
    class_name TEXT PRIMARY KEY CHECK (class_name IN ('SY', 'TY', 'Final Year'))
);

INSERT INTO public.classes (class_name) VALUES ('SY'), ('TY'), ('Final Year') ON CONFLICT DO NOTHING;

-- ----------------------------------------------------------------------------
-- 2. STUDENTS MASTER TABLE
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.students (
    registration_no TEXT PRIMARY KEY,
    roll_no TEXT NOT NULL,
    name TEXT NOT NULL,
    class_name TEXT NOT NULL REFERENCES public.classes(class_name) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_students_class ON public.students(class_name);

-- ----------------------------------------------------------------------------
-- 3. TESTS TABLE
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.tests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_number TEXT NOT NULL,
    test_name TEXT NOT NULL,
    class_name TEXT REFERENCES public.classes(class_name),
    test_date DATE NOT NULL,
    total_marks NUMERIC(6, 2) NOT NULL CHECK (total_marks > 0),
    status TEXT NOT NULL CHECK (status IN ('Upcoming', 'Current', 'Completed')),
    is_published INTEGER NOT NULL DEFAULT 0 CHECK (is_published IN (0, 1)),
    duration_minutes INTEGER NOT NULL DEFAULT 60,
    instructions TEXT DEFAULT '',
    start_time TEXT NOT NULL DEFAULT '10:00 AM',
    finish_time TEXT NOT NULL DEFAULT '11:00 AM',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tests_status ON public.tests(status);
CREATE INDEX IF NOT EXISTS idx_tests_date ON public.tests(test_date);

-- ----------------------------------------------------------------------------
-- 4. QUESTION VERSIONS TABLE
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.question_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_id BIGINT NOT NULL REFERENCES public.tests(id) ON DELETE CASCADE,
    version_number INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(test_id, version_number)
);

-- ----------------------------------------------------------------------------
-- 5. TEST QUESTIONS TABLE
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.test_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_id BIGINT NOT NULL REFERENCES public.tests(id) ON DELETE CASCADE,
    version_id BIGINT REFERENCES public.question_versions(id) ON DELETE SET NULL,
    question_number INTEGER NOT NULL,
    question_text TEXT NOT NULL,
    option_a TEXT NOT NULL,
    option_b TEXT NOT NULL,
    option_c TEXT NOT NULL,
    option_d TEXT NOT NULL,
    correct_option TEXT NOT NULL CHECK (correct_option IN ('A', 'B', 'C', 'D')),
    marks NUMERIC(6, 2) NOT NULL DEFAULT 1.0,
    is_active INTEGER NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_questions_test_id ON public.test_questions(test_id);

-- ----------------------------------------------------------------------------
-- 6. STUDENT ATTEMPTS TABLE
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.student_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_id BIGINT NOT NULL REFERENCES public.tests(id) ON DELETE CASCADE,
    registration_no TEXT NOT NULL REFERENCES public.students(registration_no) ON DELETE CASCADE,
    version_id BIGINT REFERENCES public.question_versions(id) ON DELETE SET NULL,
    attempt_status TEXT NOT NULL CHECK (attempt_status IN ('Not Started', 'In Progress', 'Submitted', 'Terminated')),
    attendance TEXT NOT NULL DEFAULT 'Absent' CHECK (attendance IN ('Present', 'Absent')),
    is_late_attempt INTEGER NOT NULL DEFAULT 0,
    violation_count INTEGER NOT NULL DEFAULT 0,
    violation_logs_json JSONB DEFAULT '[]'::jsonb,
    start_time TIMESTAMPTZ,
    end_time TIMESTAMPTZ,
    calculated_score NUMERIC(6, 2) DEFAULT 0.0,
    calculated_percentage NUMERIC(6, 2) DEFAULT 0.0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(test_id, registration_no)
);

CREATE INDEX IF NOT EXISTS idx_attempts_test_reg ON public.student_attempts(test_id, registration_no);

-- ----------------------------------------------------------------------------
-- 7. CONTINUOUS STUDENT ANSWERS TABLE
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.student_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id BIGINT NOT NULL REFERENCES public.student_attempts(id) ON DELETE CASCADE,
    question_id BIGINT NOT NULL REFERENCES public.test_questions(id) ON DELETE CASCADE,
    selected_option TEXT CHECK (selected_option IN ('A', 'B', 'C', 'D', '')),
    saved_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(attempt_id, question_id)
);

-- ----------------------------------------------------------------------------
-- 8. ATTENDANCE TABLE
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_id BIGINT NOT NULL REFERENCES public.tests(id) ON DELETE CASCADE,
    registration_no TEXT NOT NULL REFERENCES public.students(registration_no) ON DELETE CASCADE,
    status TEXT NOT NULL CHECK (status IN ('Present', 'Absent')),
    is_late_attempt INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(test_id, registration_no)
);

-- ----------------------------------------------------------------------------
-- 9. TEST RESULTS TABLE (PUBLISHED OFFICIAL RESULTS)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.test_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_id BIGINT NOT NULL REFERENCES public.tests(id) ON DELETE CASCADE,
    registration_no TEXT NOT NULL REFERENCES public.students(registration_no) ON DELETE CASCADE,
    attendance TEXT NOT NULL CHECK (attendance IN ('Present', 'Absent')),
    marks_obtained NUMERIC(6, 2) NOT NULL,
    percentage NUMERIC(6, 2) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(test_id, registration_no)
);

CREATE INDEX IF NOT EXISTS idx_results_test_reg ON public.test_results(test_id, registration_no);

-- ----------------------------------------------------------------------------
-- 10. STUDENT SCORES (LEADERBOARD / COGNIFY SCORES)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.student_scores (
    registration_no TEXT PRIMARY KEY REFERENCES public.students(registration_no) ON DELETE CASCADE,
    cognify_score NUMERIC(6, 2) NOT NULL DEFAULT 0.0,
    completed_tests_count INTEGER NOT NULL DEFAULT 0,
    rank INTEGER NOT NULL DEFAULT 0,
    class_name TEXT NOT NULL REFERENCES public.classes(class_name),
    last_updated TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_scores_class_rank ON public.student_scores(class_name, rank);

-- ----------------------------------------------------------------------------
-- 11. RESOURCES TABLE
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.resources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_id BIGINT NOT NULL REFERENCES public.tests(id) ON DELETE CASCADE,
    resource_type TEXT NOT NULL CHECK (resource_type IN ('notes', 'practice', 'question_paper', 'answer_key')),
    title TEXT NOT NULL,
    file_path TEXT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ----------------------------------------------------------------------------
-- 12. SYLLABUS TABLE
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.syllabus (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_id BIGINT NOT NULL REFERENCES public.tests(id) ON DELETE CASCADE,
    category_name TEXT NOT NULL,
    topics_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    display_order INTEGER DEFAULT 0
);

-- ----------------------------------------------------------------------------
-- 13. ADMIN SETTINGS TABLE
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.admin_settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ----------------------------------------------------------------------------
-- 14. AUDIT LOGS TABLE
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    action TEXT NOT NULL,
    test_id BIGINT,
    registration_no TEXT,
    previous_value TEXT,
    new_value TEXT
);

-- ----------------------------------------------------------------------------
-- 15. BACKUPS TABLE
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.backups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    backup_name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    file_path TEXT NOT NULL,
    size_bytes BIGINT DEFAULT 0
);

-- ----------------------------------------------------------------------------
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ----------------------------------------------------------------------------
ALTER TABLE public.classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.question_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.test_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_answers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.test_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_scores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.resources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.syllabus ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.backups ENABLE ROW LEVEL SECURITY;

-- Public Read Policies
CREATE POLICY "Public Read Classes" ON public.classes FOR SELECT USING (true);
CREATE POLICY "Public Read Students" ON public.students FOR SELECT USING (true);
CREATE POLICY "Public Read Tests" ON public.tests FOR SELECT USING (true);
CREATE POLICY "Public Read Syllabus" ON public.syllabus FOR SELECT USING (true);
CREATE POLICY "Public Read Resources" ON public.resources FOR SELECT USING (true);
CREATE POLICY "Public Read Results" ON public.test_results FOR SELECT USING (true);
CREATE POLICY "Public Read Scores" ON public.student_scores FOR SELECT USING (true);
CREATE POLICY "Public Student Attempt ReadWrite" ON public.student_attempts FOR ALL USING (true);
CREATE POLICY "Public Student Answer ReadWrite" ON public.student_answers FOR ALL USING (true);
